services:
    postgres-db:
        image: postgres:17.5
        container_name: db_postgresql
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_db: lumenif_db
        ports:
            - "5432:5432"
        volumes:
            - pg-data:/var/lib/postgresql/data
        restart: always
volumes:
    pg-data:
